project:
  type: website

website:
  title: "Statistics 243 Fall 2022"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: syllabus.md
        text: Syllabus
      - file: office_hours.md
        text: "Office hours"
      - file: schedule.md
        text: Schedule
      - file: software.md
        text: Software
      - text: "Units"
        menu:
          - file: units/unit1-unix.Rmd
            text: "Unit 1"
          - file: units/unit2-dataTech.Rmd
            text: "Unit 2"
      - href: https://edstem.org/us/courses/25090/discussion/
        text: "Discussion"
      - href: https://statistics.berkeley.edu/computing/training/tutorials
        text: Tutorials
        
output:
  html
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: article
    margin-left: 30mm
    margin-right: 30mm
    toc: true