project:
  type: website

website:
  title: "Statistics 243 Fall 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - text: "Units"
        menu:
          - units/unit1.Rmd
          - units/unit2.Rmd
      - href: edstem.org
        text: "Discussion"
       
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



