project:
  type: website

website:
  title: "Statistics 243 Fall 2022"
  navbar:
    left:
      - file: index.qmd
        text: Home
      - file: syllabus.md
        text: Syllabus
      - file: office_hours.md
        text: "Office hours"
      - file: software.md
        text: Software
      - text: "Units"
        menu:
          - file: units/unit1.Rmd
          - text: "Unit 1"
          - file: units/unit2.Rmd
      - href: https://edstem.org/us/courses/25090/discussion/
        text: "Discussion"
      - href: https://statistics.berkeley.edu/computing/training/tutorials
        text: Tutorials
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



