---
title: "Statistics 243 Fall 2022"
---

This site is UNDER CONSTRUCTION. Do not rely on materials here before August 22.

See the links above for the key resources for the course. 

## Questions about taking the class

If you would like to audit the class, enroll as a UC Berkeley undergraduate, or enroll as a concurrent enrollment student (i.e., for visiting students), or for some other reason are not enrolled, please fill out [this survey](https://forms.gle/SVm9thpkh16Zps2h6) as soon as possible. All those enrolled or wishing to take the class should have filled it out by Friday August 26 at noon.

Undergraduates can only take the course with my permission and once all graduate students have an opportunity to register. I expect there will be space, and will likely start admitting undergraduates early the week of August 29 or late the previous week.

Concurrent enrollment students can take the course with my permission and once all UC Berkeley students have had an opportunity to register. I expect there will be space, and will likely start admitting concurrent enrollment students early the week of August 29.

Please see the syllabus for the math and statistics background I expect, as well as the need to be familiar with R or to get up to speed in R during the first few weeks of the semester.

The first three weeks involve a lot of moving pieces, in part related to trying to get everyone up to speed with the bash shell and R. Please use [these notes](first_three_weeks) to keep on top of what you need to do.

## Course content

 - This site: most non-recorded course material
   - For html versions of the Units, see the navigation bar above.
   - For PDF versions of the Units, clone the [GitHub repository](https://github.com/berkeley-stat243/stat243-fall-2022), or if you're not yet familiar with Git, [download a zip file](https://github.com/berkeley-stat243/stat243-fall-2022/archive/refs/heads/main.zip).
 - [Various SCF tutorials](http://statistics.berkeley.edu/computing/training/tutorials): These include the various tutorials referred to in the class materials (e.g., the UNIX and bash shell tutorials, the dynamic documents tutorial, the Git tutorial, the string processing tutorial, etc.).
 - [bCourses](https://bcourses.berkeley.edu/courses/1507757): links to class course captures and any pre-recorded material.

If you're not yet familiar with Git, go to the upper right of this page and click on 'Clone or download' and then 'Download ZIP'.

