---
title: "Introduction to UNIX, computers, and key tools"
author: "Chris Paciorek"
date: "2022-08-15"
---


By UNIX, I mean any UNIX-like operating system, including Linux and Mac
OS X. On the Mac you can access a UNIX terminal window with the Terminal
application (via `Applications -> Utilities -> Terminal` from the
Finder). Most modern scientific computing is done on UNIX-based
machines, often by remotely logging in to a UNIX-based server.

There are a variety of ways to get access to a UNIX-style command line
environment, outlined in the software tips on the course website.


# UNIX basics

Please see the material in [our tutorial on the basics of
UNIX](https://berkeley-scf.github.io/tutorial-unix-basics) to get up
to speed on working in a UNIX-style command line environment. We'll do a
bit of demo in the first class. If what you see seems quite familiar,
you can probably skip that tutorial. If what you see is not familiar,
please work through the tutorial and (optionally) attend section on
Friday August 26 to work on the problems at the end of the tutorial and
be able to ask questins of the GSI and other students.

For an alternative introduction (which also includes some of the topics
we'll discuss in Unit 4 on shell scripting), see [this Software
Carpentry tutorial](https://swcarpentry.github.io/shell-novice).

# Version control

Version control refers to the process of keeping track of changes to
your materials on a computer, often code files but other files as well.
It generally works well with text files because version control operates
based on differences between two versions of a file, and those
differences are kept track of on a line-by-line basis. Version control
is a central concept/practice in modern scientific computing.

A very popular and powerful tool for version control is Git. We'll be
using Git extensively for version control.

More information is available in the tutorial on the basics of using
Git. You'll have a chance to work through the tutorial and practice with
Git in the first section/lab. During the course, you'll make use of Git
for submitting problem sets and for doing the final project. I recommend
you practice using it more generally while preparing your problem set
solutions.

Git stores the files for a project in a *repository*. Here are some
basic Git commands you can use to access the class materials from the
command line. There are also [graphical interfaces to
Git](https://git-scm.com/downloads) that you can explore. That said, I
recommend [Github Desktop](https://desktop.github.com), available for
Mac and Windows.

1.  To clone (i.e., copy) a repository (in this case from GitHub)
    *berkeley-stat243* is the project and *stat243-fall-2021* is the
    repository:
    ```
    git clone https://github.com/berkeley-stat243/stat243-fall-2021
    ```

2.  To update a repository to reflect changes made in a remote copy of
    the repository:
    ```
    cd /to/any/directory/within/the/local/repository
    ```
    ```
    git pull
    ```

We'll see a lot more about Git in Section sessions, where you'll learn to set up
a repository, make changes to repositories and work with local and
remote versons of the repository. The section material will follow our
tutorial on the basics of Git, Github, and version control.

Some links to more resources:

-   Git for Scientists: A Tutorial:
    <http://nyuccl.org/pages/GitTutorial/>

-   Gitwash: workflow for scientific Python projects:\
    <http://matthew-brett.github.io/pydagogue/gitwash_build.html>

-   Git branching demo: <http://pcottle.github.io/learnGitBranching/>

# Parts of a computer

We won't spend a lot of time thinking about computer hardware, but we do
need to know some of the basics that relate to using a computer and
programming effectively. There are many layers of technical detail one
could get into, but the key things for now are to have a basic
understanding of these components of a computer:

-   CPU
    -   cache
-   main memory (RAM)
-   disk

Please read [this overview](https://36-750.github.io/tools/computer-architecture/) from a
class at CMU that is similar to this class. Don't worry about too much
of the details in the "How Programs Run" section - just try to get the
main idea.

# Connecting to other machines

To connect to a remote machine, you need to use SSH. SSH is available as
`ssh` when you are on the UNIX command line. There are also SSH clients
for Windows. For more information on SSH client programs and on using
SSH, please see [this
webpage](http://statistics.berkeley.edu/computing/ssh). Here's an
example of connecting to one of the SCF machines (this assumes you have
an SCF account, which you may, and that your user name is paciorek,
which it is not).

```
ssh paciorek@radagast.berkeley.edu
```

To copy files between machines, we can use *scp*, which has similar
options to *cp*. The first command here copies a local file to a remote
machine. The second copies from a remote machine to the machine you are
on. You can use relative paths to refer to locations on the local
machine. On the remote machine all paths need to be absolute or to be
relative to your home directory on that machine. Again, this assumes you
have an SCF account.

```
scp file.txt paciorek@radagast.berkeley.edu:~/research/.
scp paciorek@radagast.berkeley.edu:/data/file.txt \
  ~/research/renamed.txt
```

There are also client programs for file transfer; see [this
webpage](http://statistics.berkeley.edu/computing/copying-files).

# Editors

For statistical computing, we need a text editor, not a word processor,
because we're going to be operating on files of code and data files
(which are plain text files), for which word processing formatting gets
in the way. **Don't use Microsoft Word or Google Docs to edit code files
or Markdown/R Markdown/LaTeX.**

## Some useful editors

-   various editors available on all operating systems:
    -   traditional editors born in UNIX: *emacs*, *vim*
    -   some newer editors: *Atom*, *Sublime Text* (Sublime is
        proprietary/not free)
-   Windows-specific: *WinEdt*
-   Mac-specific: *Aquamacs Emacs, TextMate, TextEdit*
-   RStudio provides a built-in editor for R code and R Markdown files.
    (Note: RStudio as a whole is an IDE (integrated development environment.
    The editor is just the editing window where you edit code (and R
    Markdown) files.)
-   *VSCode* has a powerful code editor that is customized to work with
    various languages.

As you get started it's ok to use a very simple text editor such as
Notepad in Windows, but you should take the time in the next few weeks
to try out more powerful editors such as one of those listed above. It
will be well worth your time over the course of your graduate work and
then your career.

Be careful in Windows - file suffixes are often hidden.

## (Optional) Basic emacs

Emacs is one option as an editor. I use Emacs a fair amount, so I'm
including some tips here, but other editors listed above are just as
good.

-   *Emacs* has special modes for different types of files: R code
    files, C code files, Latex files -- it's worth your time to figure
    out how to set this up on your machine for the kinds of files you
    often work on
    -   For working with R, ESS (emacs speaks statistics) mode is
        helpful. This is built into Aquamacs Emacs. 
-   To open emacs in the terminal window rather than as a new window,
    which is handy when it's too slow (or impossible) to pass (i.e.,
    tunnel) the graphical emacs window through ssh:
    ```
    emacs -nw file.txt 
    ```
-   Some helpful keystroke sequence shorcuts

|                      Sequence               |                             Result                     |
|----------------------------------------|-------------------------------------------------------------|
|                     `C-x,C-c`            |                            Close the file|
|                     `C-x,C-s`             |                            Save the file|
|                     `C-x,C-w`             |                        Save with a new name|
|                       `C-s`               |                               Search|
|                       `ESC`               |            Get out of command buffer at bottom of screen|
|                       `C-a`               |                       Go to beginning of line|
|                       `C-e`               |                          Go to end of line|
|                       `C-k`               |           Delete the rest of the line from cursor forward|
|       `C-space`*,* then move to end of block   |                 Highlight a block of text|
|                       `C-w`                 |   Remove the highlighted block, putting it in the kill buffer|
|       `C-y` *(*after using `C-k` or `C-w`*)*   |        Paste from kill buffer ('y' is for 'yank')|

 
